spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/user-groups/**
        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/groups/**,/group-roles/**
        - id: role-service
          uri: lb://ROLE-SERVICE
          predicates:
            - Path=/roles/**