#*** Spring Application Properties ***#
server:
  port: 8765

#*** Spring Cloud Gateway Routing to remove prefix service name from all API ***#
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/user-groups/**
        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/groups/**,/group-roles/**
        - id: role-service
          uri: lb://ROLE-SERVICE
          predicates:
            - Path=/roles/**



#*** Spring Cloud Gateway Properties (Providing custom path) hence commented ***#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true